### ISSUE TITLE
not parsable

### ISSUE THREAD

**Issue by BananaAcid** [pug-php/js-phpize#31]
Working on pugjs, I get with Phug ...

![image](https://user-images.githubusercontent.com/1894723/77824204-3c5f3580-7101-11ea-911a-ccbf8e95414b.png)

does not work either

![image](https://user-images.githubusercontent.com/1894723/77824374-8c8ac780-7102-11ea-8961-055ce2dbaf07.png)

`[].concat`, `Object.keys()` does not seem to work ...

**Comment by kylekatarnls** [comment]
Indeed, we don't have `Object.*` polyfill at all. But you can rely on PHP functions:

```pug
- tags = array_merge(tags, array_keys(attributes))
```

I know this make the mixin not compatible in JS env, but I would argue you should avoid having multiple ways of doing the same thing and attributes are not supposed to be used this way.
